# ./docker/nginx/default.conf
server {
    server_name ~.*;
    listen 8080;
    root /app/public/;

    # Anonymisation pour la documentation
    set_real_ip_from  192.168.1.0/24;
    set_real_ip_from  192.168.1.0/24;
    real_ip_header    X-Forwarded-For;
    real_ip_recursive on;

    ###
    # AJOUT SECURITE
    # 1. Cache la version de Nginx (Corrige WARN 10036)
    server_tokens off;

    # 2. Empêche le Clickjacking (Corrige WARN 10020)
    add_header X-Frame-Options "SAMEORIGIN" always;

    # 3. Empêche le sniffing de type MIME (Corrige WARN 10021)
    add_header X-Content-Type-Options "nosniff" always;

    # 4. Protection XSS pour les navigateurs (Complémentaire)
    add_header X-XSS-Protection "1; mode=block" always;

    # 5. Permissions Policy (Corrige WARN 10063)
    # On interdit l'accès caméra/micro/geoloc par défaut
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

    # 6. Referrer Policy (Bonne pratique)
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # 7. Content Security Policy (CSP) (Corrige WARN 10038)
    # ATTENTION : C'est restrictif. Si tes images/JS viennent d'ailleurs, il faudra ajuster.
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; frame-ancestors 'self'; object-src 'none'; base-uri 'self'; form-action 'self';" always;
    # FIN
    ###

    location /maildev/ {
        proxy_pass http://mailsender:1080/;
    }

    location / {
        try_files $uri /index.php$is_args$args;

        client_max_body_size 20M;
        gzip on;
        gzip_buffers 4 32k;
        gzip_min_length 1100;
        gzip_types text/plain application/x-javascript text/xml text/css;
        gzip_vary on;

        location ~ ^/index\.php(/|$) {
            fastcgi_pass php:9000;
            include fastcgi_params;
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
            fastcgi_param DOCUMENT_ROOT $realpath_root;
            fastcgi_param SCRIPT_NAME $request_uri;
            fastcgi_param SERVER_NAME $http_host;
            fastcgi_param REMOTE_ADDR $http_x_real_ip;
            fastcgi_read_timeout 2000;
        }

        location ~ \.php$ {
          return 404;
        }
    }



    location /build/ {
        if (-f $request_filename) {
            expires 30d;
            access_log off;
        }
        try_files $uri =404;
    }
}