# ./docker/nginx/default.conf
# https://images.chainguard.dev/directory/image/nginx/overview
worker_processes  auto;

error_log  /var/log/nginx/error.log notice;
pid        /var/run/nginx.pid;

events {
    worker_connections  1024;
}

http {
    include /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile        on;

    server {
        server_name ~.*;
        listen 8080;
        root /app/public/;

        set_real_ip_from  10.201.0.0/16;
        set_real_ip_from  10.202.0.0/16;
        real_ip_header    X-Forwarded-For;
        real_ip_recursive on;

        # SÉCURITÉ (OWASP ZAP Remédiation)
        server_tokens off;
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self' data:; frame-ancestors 'self'; object-src 'none'; base-uri 'self'; form-action 'self';" always;

        # GZIP GLOBAL (Profite aussi au dossier /build/)
        gzip on;
        gzip_buffers 4 32k;
        gzip_min_length 1100;
        gzip_types text/plain application/javascript text/xml text/css application/json image/svg+xml;
        gzip_vary on;

        location /maildev/ {
            proxy_pass http://mailsender:1080/;
        }

        location / {
            try_files $uri /index.php$is_args$args;
            client_max_body_size 20M;

            location ~ ^/index\.php(/|$) {
                fastcgi_pass php:9000;
                include fastcgi_params;
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
                fastcgi_param DOCUMENT_ROOT $realpath_root;
                fastcgi_param SCRIPT_NAME $request_uri;
                fastcgi_param SERVER_NAME $http_host;
                fastcgi_param REMOTE_ADDR $http_x_real_ip;
                fastcgi_read_timeout 2000;
            }

            location ~ \.php$ {
            return 404;
            }
        }

        location /build/ {
            if (-f $request_filename) {
                expires 30d;
                access_log off;
            }
            try_files $uri =404;
        }
    }
}
